name: CI

on:
  release:
    types: [published]
  push:
    branches: [ "main" ]

permissions: write-all

jobs:
  build-and-release:
    runs-on: ubuntu-24.04-arm
    container:
      image: ghcr.io/hqzing/docker-mini-openharmony:latest
      volumes:
        - /opt/node20:/__e/node20:rw,rshared
    steps:
      - name: Setup node for actions
        run: |
          curl -L -O https://github.com/hqzing/ohos-node/releases/download/v24.2.0/node-v24.2.0-openharmony-arm64.tar.gz
          mkdir /__e/node20/bin
          tar -zxf node-v24.2.0-openharmony-arm64.tar.gz -C /opt
          ln -s /opt/node-v24.2.0-openharmony-arm64/bin/node /__e/node20/bin/node
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: ./build.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ${{ github.workspace }}/ruby-3.4.5-ohos-arm64.tar.gz
      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'release'
        with:
          files: ${{ github.workspace }}/ruby-3.4.5-ohos-arm64.tar.gz
